# Generated by Django 2.2.4 on 2019-08-27 10:00

from django.db import migrations


def copy_owner_info_to_owner_model(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner_name = flat.owner
        owner_phone_pure = flat.owner_phone_pure
        owner = Owner.objects.filter(name=owner_name, phone_pure=owner_phone_pure)
        if owner.exists():
            owner.flat.add(flat)
            continue

        owner = Owner.objects.create(
            name=owner_name,
            phone_number=flat.owners_phonenumber,
            phone_pure=owner_phone_pure,
        )
        owner.flat.add(flat)


def move_backward(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Owner.objects.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20190827_1259'),
    ]

    operations = [
        migrations.RunPython(copy_owner_info_to_owner_model, move_backward)
    ]
