# Generated by Django 2.2.4 on 2019-09-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20190827_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.NullBooleanField(choices=[(None, 'Не заполнено'), (True, 'Новостройка'), (False, 'Старое здание')], verbose_name='Тип постройки'),
        ),
    ]
